# --- !Ups
create table "cats" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int,
  "color" varchar,
  "picture" varchar,
  "race" varchar,
  "gender" int not null
);

# --- !Downs
drop table "cats" if exists;
